apps/phone/urls.py
from django.conf.urls import url
from apps.phone import views


urlpatterns = [
    url(r'^$', views.test, name='test'),
    url(r'^customer/$', views.customer_list, name='customer_list'),
    url(r'^customer/create/$', views.customer_create_test, name='customer_create'),
    url(r'^customer/(?P<pk>\d+)/update/(?P<phone>\d+)$', views.customer_update, name='customer_update'),
    url(r'^customer/(?P<pk>\d+)/add_number/(?P<phone>\d+)$', views.number_create, name='number_create'),
    url(r'^customer/delete_number/(?P<phone>\d+)$', views.customer_delete, name='customer_delete')
]

settings/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.phone.urls')),
]

apps/phone/models.py
from django.db import models
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
from django.core.validators import RegexValidator

from django.core.exceptions import ValidationError

COLLECTIVE_NUMBER = ['84959830402', '84959830535']


class Customer(models.Model):
    STATUS = (
        ('1', 'Активный'),
        ('0', 'Отключен'),
    )

    name = models.CharField(max_length=255, unique=True)
    status = models.CharField(max_length=10,
                              choices=STATUS,
                              default='0')
    address = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    date_last_change = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class Device(models.Model):
    name = models.CharField(max_length=255)
    login = models.CharField(max_length=255)
    password = models.CharField('Пароль устройства', max_length=255)
    wan = models.GenericIPAddressField(protocol='IPv4', unique=True)
    lan = models.GenericIPAddressField(protocol='IPv4', blank=True, null=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.wan)


class Number(models.Model):
    REGEXP_NUMBER_AMTEL = '^8(4951089[567]\d{2}|49598304[0-2]\d|49598305[2-4]\d|4959830550)$'
    TYPE_OF_INTNUM = (
        ('SKD', 'СКД'),
        ('MTT', 'МТТ'),
        ('MOA', 'МОА'),
    )
    TYPE_OF_EXT = (
        ('any', 'общий'),
        ('specific', 'выделенный'),
        ('free', 'свободный')
    )
    internal_type = models.CharField(max_length=20,
                                     choices=TYPE_OF_INTNUM,
                                     default='MTT')
    internal_number = models.CharField(max_length=6, unique=True, validators=[RegexValidator(
        regex='^\d{6}$',
        message='Must be contain 6 digits',
        code='invalid_internal_number'
    )])

    internal_password = models.CharField(max_length=20, blank=True, null=True)
    customer = models.ForeignKey(Customer,
                                 on_delete=models.CASCADE,
                                 blank=True,
                                 null=True)
    device = models.ForeignKey(Device,
                               on_delete=models.CASCADE,
                               blank=True,
                               null=True)
    AON = models.CharField(max_length=11, blank=True, null=True, validators=[RegexValidator(
        regex=REGEXP_NUMBER_AMTEL,
        message='Must be contain AMTEL number',
        code='invalid_external_number'
    )])
    type_of_access = models.CharField(max_length=10,
                                      choices=TYPE_OF_EXT, default='free')

    def __str__(self):
        return '"{}" <=> "{}"'.format(self.internal_number, self.AON)


@receiver(pre_save, sender=Number)
def my_handler(sender, instance, **kwargs):
    instance.type_of_access = 'specific'
    if instance.AON == '':
        instance.type_of_access = 'free'
        return
    if instance.AON in COLLECTIVE_NUMBER:
        instance.type_of_access = 'any'
        return


@receiver(post_delete, sender=Number)
def remove_client_with_no_numbers(sender, instance, **kwargs):
    customer = instance.customer
    if not Number.objects.filter(customer=customer):
        print('удаление клиента')
        customer.delete()

apps/phone/forms.py
from django import forms
from apps.phone.models import Customer, Device, Number


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('name', 'status', 'address', 'description', )


class NumberForm(forms.ModelForm):
    class Meta:
        model = Number
        fields = ('internal_type',
                  'internal_number',
                  'internal_password',
                  'device',
                  'AON')


class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = (
            'name',
            'login',
            'password',
            'wan',
        )


class CreateNumberForm(forms.ModelForm):
    class Meta:
        model = Number
        fields = (
            'internal_number',
            'internal_type',
            'internal_password',
            'device',
            'AON',
        )


class TestDeviceForm(forms.Form):
    name = forms.CharField(max_length=255)
    login = forms.CharField(max_length=255)
    password = forms.CharField(max_length=255)
    wan = forms.GenericIPAddressField(protocol='IPv4')
    lan = forms.GenericIPAddressField(protocol='IPv4', required=False)


class EnhancedNumberForm(NumberForm):
    STATUS = (
        ('1', 'Активный'),
        ('0', 'Отключен'),
    )

    name = forms.CharField(max_length=255)
    status = forms.ChoiceField(choices=STATUS)
    address = forms.CharField(max_length=255)
    description = forms.CharField(max_length=255)
    device_name = forms.CharField(max_length=255)
    device_login = forms.CharField(max_length=255)
    device_password = forms.CharField(max_length=255)
    device_wan = forms.GenericIPAddressField(protocol='IPv4')
    device_lan = forms.GenericIPAddressField(protocol='IPv4', required=False)
    ArticleFormSet = forms.formset_factory(CustomerForm)

    def clean(self):
        cleaned_data = super(EnhancedNumberForm, self).clean()

        Current_device = Device()
        Current_customer = Customer()
        name = cleaned_data.get("name")
        status = cleaned_data.get("status")
        address = cleaned_data.get("address")
        description = cleaned_data.get("description")

        Current_customer.name = name
        Current_customer.status = status
        Current_customer.address = address
        Current_customer.description = description

        device_name = cleaned_data.get("device_name")
        device_login = cleaned_data.get("device_login")
        device_password = cleaned_data.get("device_password")
        device_wan = cleaned_data.get("device_wan")
        device_lan = cleaned_data.get("device_lan")

        Current_device.name = device_name
        Current_device.login = device_login
        Current_device.password = device_password
        Current_device.wan = device_wan
        Current_device.lan = device_lan

        self.instance.device = Current_device
        self.instance.customer = Current_customer
        if self.is_valid():
            self.instance.device.save()
            self.instance.customer.save()

apps/phone/views.py
from django.shortcuts import render
from django.http import HttpResponse
from apps.phone.models import Customer, Number
from apps.phone.forms import CustomerForm, NumberForm, CreateNumberForm, EnhancedNumberForm
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
# Create your views here.


def test(request):
    html = 'hello world'
    return HttpResponse(html)


def customer_list(request):
    customers = Customer.objects.all()
    return render(request, 'includes/table.html', {'customers': customers})


def save_customer(request, form_customer, form_number, template_name):
    data = dict()
    if request.method == 'POST':
        if form_customer.is_valid() and form_number.is_valid():
            customer = form_customer.save()
            post_form_number = form_number.save(commit=False)
            post_form_number.customer = customer
            post_form_number.save()
            data['form_is_valid'] = True
            customers = Customer.objects.all()
            data['html_customer_list'] = render_to_string('includes/part_list.html', {
                'customers': customers
            })
        else:
            data['form_is_valid'] = False
    context = {'form_customer': form_customer, 'form_number': form_number}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def customer_create(request):
    if request.method == 'POST':
        form_customer = CustomerForm(request.POST)
        form_number = NumberForm(request.POST)
    else:
        form_customer = CustomerForm()
        form_number = NumberForm()
    return save_customer(request, form_customer, form_number, 'includes/customer_create.html')


def customer_update(request, pk, phone):
    customer = get_object_or_404(Customer, pk=int(pk))
    number = get_object_or_404(Number, internal_number=phone)
    if request.method == 'POST':
        form_customer = CustomerForm(request.POST, instance=customer)
        form_number = NumberForm(request.POST, instance=number)
    else:
        form_customer = CustomerForm(instance=customer)
        form_number = NumberForm(instance=number)
    return save_customer(request, form_customer, form_number, 'includes/customer_update.html')


def number_create(request, pk, phone):
    data = dict()
    customer = get_object_or_404(Customer, pk=pk)
    form_number = CreateNumberForm()
    form_number.customer = customer
    if request.method == 'POST':
        form_number = CreateNumberForm(request.POST)
        if form_number.is_valid():
            post_form_number = form_number.save(commit=False)
            post_form_number.customer = customer
            post_form_number.save()
            data['form_is_valid'] = True
            data['html_customer_list'] = render_to_string('includes/part_list.html', {
                'customers': Customer.objects.all()})
        else:
            data['form_is_valid'] = False
    context = {'form_number': form_number, 'pk': pk, 'phone': phone}
    data['html_form'] = render_to_string('includes/number_create.html', context, request=request)
    return JsonResponse(data)


def customer_delete(request, phone):
    phone = get_object_or_404(Number, internal_number=phone)
    data = dict()
    if request.method == 'POST':
        phone.delete()
        data['form_is_valid'] = True
        data['html_customer_list'] = render_to_string('includes/part_list.html', {
            'customers': Customer.objects.all()
        })
    else:
        context = {'phone': phone}
        data['html_form'] = render_to_string('includes/number_delete.html', context, request=request)
    return JsonResponse(data)


def customer_create_test(request):
    data = dict()
    if request.method == 'POST':
        form_all = EnhancedNumberForm(request.POST)
        if form_all.is_valid():
            form_all.save()
            data['form_is_valid'] = True
            customers = Customer.objects.all()
            data['html_customer_list'] = render_to_string('includes/part_list.html', {
                'customers': customers
            })
        else:
            data['form_is_valid'] = False
    else:
        form_all = EnhancedNumberForm()
    context = {'form_customer': form_all}
    data['html_form'] = render_to_string('includes/customer_create.html', context, request=request)
    return JsonResponse(data)

apps/phone/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Table</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% include 'includes/header.html' %}
    <div class="container-fluid">
      {% block content %}
      {% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block javascript %}
{% endblock %}
  </body>
</html>

apps/phone/templates/table.html
{% extends 'base.html' %}
{% block content %}

  <h1 class="page-header">Распределение телефонных номеров</h1>

      <!-- BUTTON TO TRIGGER THE ACTION -->
  <p>
    <button type="button" class="btn btn-primary js-create-book">
      <span class="glyphicon glyphicon-plus"></span>
      Добавить
    </button>
  </p>
  <table class="table" id="book-table">
    <thead>
      <tr>
        <th>#</th>
          <th>Внутренний номер</th>
          <th>Имя клиента</th>
          <th>Статус</th>
          <th>Адрес</th>
          <th>Описание клиента</th>
          <th>Дата</th>
          <th>Тип номера</th>
          <th>Пароль внутреннего номера</th>
          <th>Устройство</th>
          <th>Логин</th>
          <th>Пароль</th>
          <th>IP Адрес</th>
          <th>Внешний номер</th>
          <th>Тип номера</th>
      </tr>
    </thead>
    <tbody>
      {% for customer in customers %}
          {% for number in customer.number_set.all %}
            <tr>
                <td>{{ number.id }}</td>
                <td>{{ number.internal_number }}</td>
                <td>{{ customer.name }}</td>
                <td>{{ customer.get_status_display }}</td>
                <td>{{ customer.address }}</td>
                <td>{{ customer.description }}</td>
                <td>{{ customer.date_last_change }}</td>
                <td>{{ number.internal_type }}</td>
                <td>{{ number.internal_password }}</td>
                <td>{{ number.device.name }}</td>
                <td>{{ number.device.login }}</td>
                <td>{{ number.device.password }}</td>
                <td>{{ number.device.wan }}</td>
                <td>{{ number.AON }}</td>
                <td>{{ number.get_type_of_access_display }}</td>
            </tr>
          {% endfor %}
            {% empty %}
            <tr>
              <td colspan="15" class="text-center bg-warning">No Customers</td>
            </tr>
      {% endfor %}
    </tbody>
  </table>

    <div class="modal fade" id="modal-book">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}